In [1]:
%run Package_AND_Parameter.ipynb
%run Feature_Selection_Methods.ipynb
%run Smoothing.ipynb

C:\Users\vita7\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


# READ TRAINING DATA

In [2]:
tr_df = pd.read_csv('training_dataframe_BasicAfterCross.csv', header=[0,1], index_col=[0,1])
tr_df.index.names = ['epoch','condition']
tr_df.reset_index(level = 1,inplace = True)

train_X = tr_df.drop(columns=['condition'])
train_Y = tr_df['condition']

C:\Users\vita7\Anaconda3\lib\site-packages\pandas\core\generic.py:3946: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  new_axis = axis.drop(labels, errors=errors)


In [3]:
train_X.head()

Function        STD                                                     \
Band     EEG Fpz-Cz EEG Fpz-Cz Delta EEG Fpz-Cz Theta EEG Fpz-Cz Alpha   
epoch                                                                    
2748      26.407742        24.255235         7.452625         3.497335   
2749      25.602262        24.284328         8.449343         2.863765   
2750      30.281923        28.666450         8.186485         3.018491   
2751      24.376224        23.349960         7.907419         2.864568   
2752      26.753053        25.842193         7.864009         2.899630   

Function                                                                 \
Band     EEG Fpz-Cz Sigma EEG Fpz-Cz Beta EEG Fpz-Cz DOR EEG Fpz-Cz TOR   
epoch                                                                     
2748             2.993339        4.003112       0.918490       0.282214   
2749             2.823556        4.160339       0.948523       0.330023   
2750             2.588744        3.531993       0.946652       0.270342   
2751             2.619738        3.676364       0.957899       0.324391   
2752             2.231749        3.238686       0.965953       0.293948   

Function                                ...       AutoCorr                 \
Band     EEG Fpz-Cz AOR EEG Fpz-Cz SOR  ... EEG Fpz-Cz TDR EEG Fpz-Cz ADR   
epoch                                   ...                                 
2748           0.132436       0.113351  ...       0.945708       0.824932   
2749           0.111856       0.110285  ...       0.953856       0.833198   
2750           0.099680       0.085488  ...       0.949807       0.824668   
2751           0.117515       0.107471  ...       0.957307       0.821846   
2752           0.108385       0.083420  ...       0.955466       0.828709   

Function                                                              \
Band     EEG Fpz-Cz SDR EEG Fpz-Cz BDR EEG Fpz-Cz ATR EEG Fpz-Cz STR   
epoch                                                                  
2748           0.677922       0.126326       0.872291       0.716841   
2749           0.645946       0.160397       0.873505       0.677195   
2750           0.673457       0.124984       0.868248       0.709046   
2751           0.671946       0.134085       0.858498       0.701913   
2752           0.685718       0.161187       0.867335       0.717679   

Function                                                              
Band     EEG Fpz-Cz BTR EEG Fpz-Cz SAR EEG Fpz-Cz BAR EEG Fpz-Cz BSR  
epoch                                                                 
2748           0.133578       0.821791       0.153135       0.186343  
2749           0.168156       0.775261       0.192508       0.248313  
2750           0.131589       0.816640       0.151557       0.185586  
2751           0.140065       0.817606       0.163151       0.199548  
2752           0.168700       0.827453       0.194504       0.235063  

[5 rows x 210 columns]

### Pick

In [4]:
fn = pd.read_csv('features_name_dataframe.csv',header=0)
fn_ = [(i,j) for i,j in zip(fn['function'],fn['band'])]
fn.head()
train_X = train_X[fn_]

In [5]:
train_X.head()

Function        STD Hjorth_complexity            STD     PtP_Amp  \
Band     EEG Fpz-Cz    EEG Fpz-Cz AOR EEG Fpz-Cz ADR  EEG Fpz-Cz   
epoch                                                              
2748      26.407742          0.231468       0.144189  167.934896   
2749      25.602262          0.238435       0.117926  153.949541   
2750      30.281923          0.196678       0.105297  188.147338   
2751      24.376224          0.243061       0.122680  145.623302   
2752      26.753053          0.226135       0.112205  154.736574   

Function                                     SVD_entropy            Power  \
Band     EEG Fpz-Cz Beta EEG Fpz-Cz ATR EEG Fpz-Cz Theta EEG Fpz-Cz Theta   
epoch                                                                       
2748           44.144581       0.356386         0.861388        86.538683   
2749           45.315804       0.271164         0.830622       200.653428   
2750           24.239070       0.389205         0.836465       179.869282   
2751           28.603751       0.367766         0.825780       163.543750   
2752           31.306376       0.320431         0.828537       176.482817   

Function     SVD_entropy                 ...     Spect_slop Sample_entropy  \
Band     EEG Fpz-Cz Beta EEG Fpz-Cz TOR  ... EEG Fpz-Cz STR EEG Fpz-Cz BAR   
epoch                                    ...                                 
2748            1.469113       0.970318  ...       0.148612       2.473788   
2749            1.462998       0.919534  ...       0.045214       2.131966   
2750            1.465026       1.055350  ...       0.059970       2.625760   
2751            1.464386       0.920081  ...       0.073556       2.442390   
2752            1.442287       1.013698  ...       0.046801       2.409593   

Function   AutoCorr     Spect_slop   Mean_frequency                   \
Band     EEG Fpz-Cz EEG Fpz-Cz BSR EEG Fpz-Cz Delta EEG Fpz-Cz Sigma   
epoch                                                                  
2748       0.966743       0.243331         1.219523        13.067572   
2749       0.964581       0.524335         1.414999        13.903433   
2750       0.977667       0.288481         1.277990        13.037165   
2751       0.965642       0.352787         1.775817        13.130978   
2752       0.974621       0.471371         1.716855        12.923802   

Function                      AutoCorr                                
Band     EEG Fpz-Cz TDR EEG Fpz-Cz SDR EEG Fpz-Cz BTR EEG Fpz-Cz BAR  
epoch                                                                 
2748           4.465962       0.677922       0.133578       0.153135  
2749           3.672738       0.645946       0.168156       0.192508  
2750           4.035992       0.673457       0.131589       0.151557  
2751           2.795504       0.671946       0.140065       0.163151  
2752           2.937640       0.685718       0.168700       0.194504  

[5 rows x 23 columns]

# ENCODING & MODEL GENERATING

In [6]:
testing_eps = np.sum(pd.read_csv('testing_records_epochs.csv',header=0))
training_eps = int(len(train_X)-testing_eps*3)

In [7]:
# Label encoding for toget
dataY = LabelEncoder().fit_transform(train_Y)
trY = dataY[:training_eps]
teY = dataY[training_eps:]

# Encoding
dataX = StandardScaler().fit_transform(train_X)
trX = dataX[:training_eps]
teX = dataX[training_eps:]
estimator = LinearDiscriminantAnalysis()

print(estimator.get_params)
print(trX.shape)
print(teX.shape)

<bound method BaseEstimator.get_params of LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
                           solver='svd', store_covariance=False, tol=0.0001)>
(95874, 23)
(31737, 23)


In [8]:
print('Sleep stage W = label:',np.unique(dataY[np.where(tr_df['condition'] == 'Sleep stage W')[0]]))
print('Sleep stage 1 = label:',np.unique(dataY[np.where(tr_df['condition'] == 'Sleep stage 1')[0]]))
print('Sleep stage 2 = label:',np.unique(dataY[np.where(tr_df['condition'] == 'Sleep stage 2')[0]]))
print('Sleep stage 3/4 = label:',np.unique(dataY[np.where(tr_df['condition'] == 'Sleep stage 3/4')[0]]))
print('Sleep stage R = label:',np.unique(dataY[np.where(tr_df['condition'] == 'Sleep stage R')[0]]))

Sleep stage W = label: [4]
Sleep stage 1 = label: [0]
Sleep stage 2 = label: [1]
Sleep stage 3/4 = label: [2]
Sleep stage R = label: [3]


# VISUALIZATION AND FEATURE CLEANING

In [16]:
clf_name = 'kNN'
clf = KNN(0.05)
clf.fit(trX)
outlier_pred = clf.labels_
outlier_scores = clf.decision_scores_

In [17]:
train_outlier_idx = np.where(outlier_pred==1)[0]

# FEATURES SELECTION

### Kruskal-wallis

In [1361]:
idx = Kruskal_Wallis_Selection_Method(data=trX, condition=23)

23


### Combine

In [1362]:
"""
idx = list(set(idx))
trX = trX[:,idx]
teX = teX[:,idx]
features_name = [list(tr_df.columns)[i+1] for i in idx]
features_name_dataframe = pd.DataFrame(features_name)
features_name_dataframe.columns = ['function','band']
features_name_dataframe.to_csv('features_name_dataframe.csv',index=0)
print(trX.shape)
print(teX.shape)
print(features_name)
"""

"\nidx = list(set(idx))\ntrX = trX[:,idx]\nteX = teX[:,idx]\nfeatures_name = [list(tr_df.columns)[i+1] for i in idx]\nfeatures_name_dataframe = pd.DataFrame(features_name)\nfeatures_name_dataframe.columns = ['function','band']\nfeatures_name_dataframe.to_csv('features_name_dataframe.csv',index=0)\nprint(trX.shape)\nprint(teX.shape)\nprint(features_name)\n"

# FIT MODEL (K-FOLD)

In [1363]:
kp = REPORT(estimator=estimator,X=trX,Y=trY,kf=5)

              precision    recall  f1-score   support

           0       0.36      0.21      0.26       395
           1       0.90      0.87      0.88      2581
           2       0.85      0.87      0.86       790
           3       0.64      0.84      0.73      1066
           4       0.90      0.83      0.86      1560

    accuracy                           0.81      6392
   macro avg       0.73      0.72      0.72      6392
weighted avg       0.82      0.81      0.81      6392

0.7472296917939778
              precision    recall  f1-score   support

           0       0.28      0.20      0.23       348
           1       0.89      0.87      0.88      2537
           2       0.88      0.85      0.86       814
           3       0.65      0.85      0.74      1097
           4       0.90      0.82      0.86      1596

    accuracy                           0.82      6392
   macro avg       0.72      0.72      0.71      6392
weighted avg       0.82      0.82      0.81      6392

0.7

# TRAINING & SAVE MODEL

In [1364]:
clf = LinearDiscriminantAnalysis()
clf.fit(trX,trY)
with open('LDA_BASIC.pickle','wb') as f:
     pickle.dump(clf, f)

# CALL MODEL

## EM Smoothing

* 平穩性平滑
* R&K準則平滑
* 眾數濾波器

In [1365]:
pickle_in = open('LDA_BASIC.pickle', 'rb')
clf = pickle.load(pickle_in)
score = clf.decision_function(teX)
n = len(teX)
pred1, label , score = smoothing(estimator=clf, score=score, n=n, label=teY)
pred2 = smoothingII(pred1)
pred = smoothingIII(pred2)

In [1366]:
print(classification_report(y_pred=pred, y_true=label))
print(confusion_matrix(y_true=label, y_pred=pred))
print(cohen_kappa_score(pred, label))

del pickle_in, clf, n
gc.collect()

              precision    recall  f1-score   support

           0       0.35      0.20      0.25       478
           1       0.86      0.84      0.85      3606
           2       0.88      0.79      0.83      1466
           3       0.71      0.85      0.77      1723
           4       0.91      0.93      0.92      3306

    accuracy                           0.83     10579
   macro avg       0.74      0.72      0.73     10579
weighted avg       0.83      0.83      0.83     10579

[[  95   62    1  240   80]
 [  29 3032  157  282  106]
 [   0  229 1164    1   72]
 [  26  191    0 1470   36]
 [ 123   30    1   90 3062]]
0.7745040216494893


37478

In [1367]:
print('Kappa:')
for k in kp:
    print(k)

print('Kappa testing:',cohen_kappa_score(pred, label))

Kappa:
0.7472296917939778
0.7485592022778107
0.7471270384965947
0.7486314466313854
0.7513332785480175
Kappa testing: 0.7745040216494893
